; ==================== PICO W (Original) with Seengreat ====================
[env:picow_seengreat]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2w
framework = arduino
board_build.filesystem = littlefs
board_build.filesystem_size = 1m

build_flags =
    -DBOARD_SEENGREAT
    -DPICO_CYW43_SUPPORTED=1
    -DCYW43_LWIP=1
    -I src

lib_deps =
    adafruit/Adafruit Protomatter @ ^1.7.0
    adafruit/Adafruit GFX Library @ ^1.11.9
    mikalhart/TinyGPSPlus @ ^1.0.3
    bblanchon/ArduinoJson @ ^6.21.5

upload_protocol = picotool
monitor_speed = 115200
